# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileCenter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MobileCenter
  pod 'RNMobileCenter', '~> 0.4.0'
  pod 'MobileCenter', '~> 0.6.0'

  

  target 'MobileCenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MobileCenter-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MobileCenter-tvOS

  target 'MobileCenter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
